[GENERAL]
SIM_TIME = 1440
N_REPLICAS = 100

CAPACIDAD_BATERIA_KWH = 50
POTENCIA_CR_KW = 50
POTENCIA_CSR_KW = 22

ARRIBO_GAMMA_SHAPE = 3
ARRIBO_GAMMA_SCALE = 12

BATERIA_MU = 32
BATERIA_SIGMA = 15

BETA_ALPHA = 20
BETA_BETA = 2

# =========================
# ESCENARIO 1: REAL
# =========================
[ESCENARIO_REAL]
CCR = 1
CCSR = 1
PROB_CR = 0.7403

# =========================
# ESCENARIO 2: EFICIENTE
# =========================
[ESCENARIO_EFICIENTE]
CCR = 1
CCSR = 2
PROB_CR = 0.7403

# =========================
# ESCENARIO 3: NO EFICIENTE
# =========================
[ESCENARIO_NO_EFICIENTE]
CCR = 1
CCSR = 3
PROB_CR = 0.7403

