[GENERAL]
SIM_TIME = 300    
SEED = 42

# =========================
# ESCENARIO 1: REAL
# =========================
[ESCENARIO_REAL]
LAMBDA_LLEGADAS = 0.0833   ; 1 cada 12 minutos
CCR = 1                 ; cargadores rápidos
CCSR = 2                ; cargadores semi-rápidos

PROB_CR = 0.7403